### ISSUE TITLE
Feedback regarding commits #1 to #3

### ISSUE THREAD

**Issue by giorgostheo** [basilhskk/miniDB#1]
## Things that should be fixed:

* pep (2 empty lines before each function with or without decorator and no paren in ifs)
* lists with every function in the decorator is not practical
  a nicer way would be to either introduce a naming scheme where (_something)
  is admin only or use some other technique to state the scope inside the func
  i.e. _lock for should be admin only - find a way to state that inside _lock
* funcs order is not intuitive and is difficult to read
* if if if is ugly - 7 indents are too much... try making it a bit prettier
* drop db no privileges? Check every func for priviledges
* "blind" excepts like 152 and 155 are not secure...
  reproduce the error and catch the specific exceptions
* replace sys exit with raise exception or warning
* chech if None should be var is (not) None not var==(!=)None 
* add code to separate file and import it 

## Things i would like to see:

* why decorators before every func? Alternatives? Decorate all functions of file?
* is this implementation generally secure?

**Comment by basilhskk** [comment]
Done all of the above and I introduced a system that you set the minimum privileges for each function. Furthermore, end-user is not allowed to call private functions that start with "_" except _update which needs to be renamed to update.
